version: '3'

services:

  db:
    image: i18nsite/mariadb
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_PASSWORD: ${MYSQL_PWD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PWD}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./mnt/backup/mariadb:/backup
      - ./mnt/data/mariadb:/var/lib/mysql
      - ./conf/init/mariadb:/docker-entrypoint-initdb.d
