CREATE TABLE `cronErr` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,`cron_id` INT UNSIGNED NOT NULL,`code` INT NOT NULL,`msg` MEDIUMBLOB NOT NULL,`ts` BIGINT UNSIGNED NOT NULL,PRIMARY KEY (`id`)
);