CREATE TABLE `cron` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,`dir` VARBINARY(255) NOT NULL,`sh` VARBINARY(255) NOT NULL,`minute` MEDIUMINT UNSIGNED NOT NULL,`timeout` MEDIUMINT UNSIGNED NOT NULL,`next` BIGINT UNSIGNED NOT NULL DEFAULT 0,`preok` BIGINT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY (`id`),UNIQUE KEY `dirsh` (`dir`,`sh`)
);