name: api

on:
  push:
    branches:
      - main
    paths:
      - rust/srv/Cargo.toml
  workflow_dispatch:

jobs:
  build:
    permissions:
      actions: write
      repository-projects: write
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      name: api
    secrets: inherit
